### ISSUE TITLE
<Severe> Bug: Error when trying to register new user 

### ISSUE THREAD

**Issue by alexiscatnip** [keenlok/look4makan#7]
Steps to Replicate:

0) run init.sql and triggers.sql
1) Sign up a new user with these credentials:
tester tester tester tester
2) Error page is shown:
![image](https://user-images.githubusercontent.com/42345054/55981069-8a004980-5cc8-11e9-9c3d-f4808247d9fb.png)

"Failed to deserialize user out of session
Error: Failed to deserialize user out of session"

Node terminal's Log: 

> GET / 200 106.544 ms - 30044
> GET /stylesheets/style.css 200 15.541 ms - 152
> GET /stylesheets/landing-page.min.css 200 19.369 ms - 1933
> GET /stylesheets/vendor/fontawesome-free/css/all.css 200 22.480 ms - 73344
> GET /stylesheets/vendor/simple-line-icons/css/simple-line-icons.css 200 24.521 ms - 13736
> GET /img/bg-masthead.jpg 404 4.277 ms - 1056
> GET /favicon.ico 404 3.755 ms - 1056
> GET /signin 200 2.728 ms - 4350
> GET /stylesheets/style.css 304 3.933 ms - -
> GET /stylesheets/landing-page.min.css 304 8.286 ms - -
> GET /stylesheet/vendor/fontawesome-free/css/all.min.css 404 6.022 ms - 1056
> GET /stylesheet/vendor/simple-line-icons/css/simple-line-icons.css 404 6.859 ms - 1056
> GET /register 200 3.021 ms - 5776
> GET /stylesheets/style.css 304 5.231 ms - -
> GET /stylesheets/landing-page.min.css 304 4.209 ms - -
> GET /stylesheet/vendor/fontawesome-free/css/all.min.css 404 3.138 ms - 1056
> GET /stylesheet/vendor/simple-line-icons/css/simple-line-icons.css 404 5.255 ms - 1056
> POST /reg_user 302 136.987 ms - 46
> { error: insert or update on table "awards" violates foreign key constraint "awards_username_fkey"
>     at Connection.parseE (C:\sourcetree_clones\look4makan\node_modules\pg\lib\connection.js:601:11)
>     at Connection.parseMessage (C:\sourcetree_clones\look4makan\node_modules\pg\lib\connection.js:398:19)
>     at Socket.<anonymous> (C:\sourcetree_clones\look4makan\node_modules\pg\lib\connection.js:120:22)
>     at Socket.emit (events.js:189:13)
>     at addChunk (_stream_readable.js:284:12)
>     at readableAddChunk (_stream_readable.js:265:11)
>     at Socket.Readable.push (_stream_readable.js:220:10)
>     at TCP.onStreamRead [as onread] (internal/stream_base_commons.js:94:17)
>   name: 'error',
>   length: 255,
>   severity: 'ERROR',
>   code: '23503',
>   detail: 'Key (username)=(tester) is not present in table "diners".',
>   hint: undefined,
>   position: undefined,
>   internalPosition: undefined,
>   internalQuery: undefined,
>   where: undefined,
>   schema: 'public',
>   table: 'awards',
>   column: undefined,
>   dataType: undefined,
>   constraint: 'awards_username_fkey',
>   file: 'ri_triggers.c',
>   line: '2851',
>   routine: 'ri_ReportViolation' }
> User does not exists?

**Comment by alexiscatnip** [comment]
can anyone replicate? or just me?
